apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webpages.devopscon.web.io
spec:
  group: devopscon.web.io
  names:
    kind: WebPage
    plural: webpages
    singular: webpage
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                content:
                  type: string
                replicas:
                  type: integer